// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_-irT1zf6l9KIJ7piIgIuSHXCdtZv7H8',
    appId: '1:105555568651:web:737130dac85eaab678bf0e',
    messagingSenderId: '105555568651',
    projectId: 'simanja-ac9ae',
    authDomain: 'simanja-ac9ae.firebaseapp.com',
    storageBucket: 'simanja-ac9ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxLsYVkn_HejwY8lv0qTxDkZ-lZl9jCGU',
    appId: '1:105555568651:android:226567d0d6adedaa78bf0e',
    messagingSenderId: '105555568651',
    projectId: 'simanja-ac9ae',
    storageBucket: 'simanja-ac9ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALncWvQ6OTfJAlqwqInlQ7D4-cnnGcXo8',
    appId: '1:105555568651:ios:6ee0ec8efd0ee26f78bf0e',
    messagingSenderId: '105555568651',
    projectId: 'simanja-ac9ae',
    storageBucket: 'simanja-ac9ae.firebasestorage.app',
    iosBundleId: 'com.gs.simanja',
  );
}
